### ISSUE TITLE
Implement TweetPHP

### ISSUE THREAD

**Issue by Felli** [WebCrew/HumHub-Twitter-Module#3]
Wondering if it would be a better idea to use [TweetPHP](https://github.com/jnicol/tweet-php) over iframe option?

**Comment by WebCrew** [comment]
yeah Tweet PHP would be a nice option and would make the setup of the module a lot easier for endusers. If you want try it then do it Sarah :)

**Comment by Felli** [comment]
I'll start trying to implement when I have time. :+1:
